#!/bin/sh
#
#       p6.sh
#       
#       Copyright 2011 Fco Javier Lucena <fran.lucena@gmail.com>
#       
#       GIS is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 3 of the License, or
#       (at your option) any later version.
#       
#       GIS is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with GIS; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

# 
# Calculo del mapa f$2 a partir del f$1 y de los mapas de parametros
#

#echo FALTAN INSTRUCCIONES PARA CALCULAR AVANCE DEL FUEGO @@

#Hay celdas ardiendo??
r.mapcalc "noroeste=if(solo_prenden > 0 && ((f$1[-1,-1] > 3 && f$1[-1,-1] < 7) || (f$1[0,-1] > 3 && f$1[0,-1] < 7)|| (f$1[-1,0] > 3 && f$1[-1,0] < 7)), f$1 + 1, f$1)"

#Incrementar celdas que arden
r.mapcalc "f$2=if(noroeste < 4, if(solo_prenden == noroeste, 4, noroeste + 1), if(noroeste < 7, if(solo_arden == noroeste, 7, noroeste + 1), if(noroeste != 0, 7, 7)))"

r.mapcalc "f$2=if(f$1 < 3, if(noroeste == 1, f$1 + 1, f$1), if(f$1 < 7, f$1 + 1, f$1))"
r.mapcalc "f$2=if(f$1 < 4, if(noroeste == 1, if(solo_prenden == f$1, 4, f$1 + 1), f$1), if(f$1 < 7, if(noroeste == 1, if(solo_prenden == f$1, 7, f$1 + 1), f$1)))"

# Asignar paleta de colores al mapa nuevo

r.colors f$2 rast=f$1 >/dev/null  2>/dev/null 

#
# Dibujo del incendio sobre landcover.30m
#
d.rast landcover.30m

d.rast -o f$2 >/dev/null  2>/dev/null
